### ISSUE TITLE
корректная отработка случая переименовывания базы

### ISSUE THREAD

**Issue by MaximBoguk** [dataegret/pg_index_watch#1]
Надо по аналогии как oid обработку для переименовывания индексов добавляли (когда основной id индекса это не имя а oid)
добавить обработку случая переименовывания базы в целом (в pg_database есть колонка oid которая в случае переименования базы не меняется).
Иначе после переименовывания крупной базы - происходит полная совершенно ненужная реиндексаций её.

**Comment by ninabel** [comment]
См. https://github.com/dataegret/pg_index_watch/pull/2

В get_index_bloat_estimates добавлено:
SELECT oid FROM pg_database d WHERE d.datname = _datname INTO _datid;
и дальнейшая проверка уже по этому datid.
